### ISSUE TITLE
No module named 'homeassistant.components.template.media_player

### ISSUE THREAD

**Issue by tiagofreire-pt** [Sennevds/media_player.template#2]
I'm using HA 0.111.4 with this custom_component.

I've put the files correctly within the custom_components folder:

![imagem](https://user-images.githubusercontent.com/41837236/85228000-a6be0400-b3d8-11ea-98e6-0796148ea18c.png)

And I'm using this yaml configuration:

```yaml
media_player:
  - platform: template
    media_players:
      hisense_tv:
        friendly_name: 'Hisense H43B7320'
        current_source_template: "{{ states('sensor.tv_source') }}"
        value_template: >
          {% if is_state('device_tracker.hisense_tv', 'home') %}
            {{ 'on' }}
          {% else %}
            {{ 'off' }}
          {% endif %}
        turn_on:
          service: switch.turn_on
          entity_id: switch.hisense_tv
        turn_off:
          service: switch.turn_off
          entity_id: switch.hisense_tv
        volume_up:
          service: script.executa_hisense_volume_up
        volume_down:
          service: script.executa_hisense_volume_down
        input_templates:
          TV:
            service: script.executa_hisense_input_tv
          HDMI 1:
            service: script.executa_hisense_input_hdmi_1
          HDMI 2:
            service: script.executa_hisense_input_hdmi_2
          HDMI 3:
            service: script.executa_hisense_input_hdmi_3
          Netflix:
            service: script.executa_hisense_netflix
          Home:
            service: script.executa_hisense_home
```

But I get this error message when checking the configuration:

```
Platform error media_player.template - No module named 'homeassistant.components.template.media_player'
```

**Comment by J-Pipe** [comment]
I get this same error

**Comment by Sennevds** [comment]
You need to copy all the *.py files from the original installation (or copy them from here https://github.com/home-assistant/core/tree/dev/homeassistant/components/template)

**Comment by J-Pipe** [comment]
Didn't seem to fix it :(
![Capture](https://user-images.githubusercontent.com/1396191/85354909-321ac080-b4d1-11ea-981c-e18544b2a4d9.JPG)

**Comment by Sennevds** [comment]
Could you also add the manifest.json file and try again?

**Comment by J-Pipe** [comment]
That did not have a affect
![Capture](https://user-images.githubusercontent.com/1396191/85473495-f1768200-b578-11ea-93eb-4ae6bafe4803.JPG)

**Comment by Sennevds** [comment]
Hmm could you check your log file if there's any more information?

**Comment by J-Pipe** [comment]
If I try to restart, it just shows the same thing in the log.

**Comment by Sennevds** [comment]
Which version off hass are you running?

**Comment by tiagofreire-pt** [comment]
I'm using the last one: 0.111.4.

**Comment by Sennevds** [comment]
@tiagofreire-pt did you also copied all the file like J-Pipe did?

**Comment by tiagofreire-pt** [comment]
Yes, I did. All of them, one by one, copy-paste by github raw mode.

**Comment by J-Pipe** [comment]
Any other suggestions?

**Comment by fufs** [comment]
You can fix it by changing the name of the component from template to for example media_template. So rename the folder in custom_components from template to whatever you want and change in configuration.yaml set platform to that name. It solved this issue for me.

**Comment by fufs** [comment]
Ok, my solution creates another problem, where other templates (switches, sensors, etc.) try to use this component (I think)

> Platform error switch.template - No module named 'custom_components.media_template.switch'

@Sennevds When creating a custom component, you should give it a unique name as well as your own manifest.json and __init__.py

**Comment by Sennevds** [comment]
Yeah someone already said that. First I thought to create this component and maybe try to add it to core but I haven't had enough time.
I will change it to behave like a completly new component

**Comment by fufs** [comment]
Create a second branch for the core implementation and leave custom_components version on master. This way if someone from home assistant would like to help you implement it, they'd have a starting point

**Comment by Sennevds** [comment]
The name of the custom component is changed to media_player_template!

**Comment by Sennevds** [comment]
@tiagofreire-pt did you test the latest version?

**Comment by tiagofreire-pt** [comment]
With the updated code, now I get a different error:

`
   Invalid config for [media_player.media_player_template]: [input_templates] is an invalid option for [media_player.media_player_template]. Check: media_player.media_player_template->media_players->hisense_tv->input_templates. (See ?, line ?). 
`

```yaml
media_player:
  - platform: media_player_template
    media_players:
      hisense_tv:
        friendly_name: 'Hisense H43B7320'
        current_source_template: "{{ states('sensor.tv_source') }}"
        value_template: >
          {% if is_state('device_tracker.hisense_tv', 'home') %}
            {{ 'on' }}
          {% else %}
            {{ 'off' }}
          {% endif %}
        turn_on:
          service: switch.turn_on
          entity_id: switch.hisense_tv
        turn_off:
          service: switch.turn_off
          entity_id: switch.hisense_tv
        volume_up:
          service: script.executa_hisense_volume_up
        volume_down:
          service: script.executa_hisense_volume_down
        input_templates:
          TV:
            service: script.executa_hisense_input_tv
          HDMI 1:
            service: script.executa_hisense_input_hdmi_1
          HDMI 2:
            service: script.executa_hisense_input_hdmi_2
          HDMI 3:
            service: script.executa_hisense_input_hdmi_3
          Netflix:
            service: script.executa_hisense_netflix
          Home:
            service: script.executa_hisense_home
```
