### ISSUE TITLE
feature request: "Browse_Media"

### ISSUE THREAD

**Issue by pho084** [Sennevds/media_player.template#50]
Hi 
first of thanks for this awesome integration.

it would be great if the "browse_media" function could be implemented

clicking this on the native media_player integration would open HomeAssistant's media section (c.f. screenshot below -- not my screenshot)
![Screenshot 2024-01-21 163820](https://github.com/Sennevds/media_player.template/assets/62800187/eb4b197b-338a-4952-b592-394f995ff753)

**Comment by Dawidooox** [comment]
I also want this feature to be implemented, but I guess it can take some time to make it, so I found a workaround of this problem. You can combine media_player.template with [Universal media player](https://www.home-assistant.io/integrations/universal/) integration to take advantage of the features of both. 

Just use your media_player.template entity as a first child in Universal media player and make sure to properly override browse_media_entity and play_media command to the media player, that supports it.

Here is a small code snippet (media_player.android_tv_template is an entity from media_player.template integration):
```
- platform: universal
  name: My Universal Media Player
  unique_id: my_universal_media_player
  device_class: tv
  children:
    - media_player.android_tv_template
    - media_player.android_tv
  browse_media_entity: media_player.android_tv
  commands:
    play_media:
      service: media_player.play_media
      target:
        entity_id: media_player.android_tv
      data:
        media_content_id: "{{ media_content_id }}"
        media_content_type: "{{ media_content_type }}"
```
